#!/usr/bin/env bash
# Render child env files from /etc/sentinel/sentinel-x.env
#
#   sudo bash deploy/config/sentinel-config-apply.sh [--discover] [--reload] [--with-ui] [--with-api] [--with-prom-sync]
#
set -euo pipefail

ROOT="${SENTINEL_ROOT:-/opt/sentinel-x}"
# shellcheck source=lib/paths.sh
. "${ROOT}/deploy/config/lib/paths.sh"
ENV_MASTER="${SENTINEL_X_ENV:-/etc/sentinel/sentinel-x.env}"
DO_DISCOVER=0
DO_RELOAD=0
WITH_UI=0
WITH_API=0
WITH_PROM_SYNC=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --discover) DO_DISCOVER=1 ;;
    --reload) DO_RELOAD=1 ;;
    --with-ui) WITH_UI=1 ;;
    --with-api) WITH_API=1 ;;
    --with-prom-sync) WITH_PROM_SYNC=1 ;;
    --env-file) ENV_MASTER="$2"; shift ;;
    -h|--help)
      echo "Usage: sentinel-config-apply.sh [--discover] [--reload] [--with-ui] [--with-api] [--with-prom-sync]"
      exit 0
      ;;
    *) echo "Unknown: $1" >&2; exit 1 ;;
  esac
  shift
done

# shellcheck source=lib/config-common.sh
. "${DEPLOY_CONFIG}/lib/config-common.sh"

[[ "$(id -u)" -eq 0 ]] || config_die "run as root (sudo)"
[[ -f "$ENV_MASTER" ]] || config_die "missing $ENV_MASTER — copy deploy/config/sentinel-x.env.example"

if [[ "$DO_DISCOVER" -eq 1 ]]; then
  bash "${DEPLOY_CONFIG}/sentinel-config-discover.sh" --write --env-file "$ENV_MASTER"
fi

config_strip_crlf "$ENV_MASTER"
# shellcheck disable=SC1090
set -a
source <(grep -v '^\s*#' "$ENV_MASTER" | grep -v '^\s*$' || true)
set +a

SENTINEL_ROOT="${SENTINEL_ROOT:-$ROOT}"
CLUSTER_ID="${CLUSTER_ID:-k3s-prod}"
NAMESPACE="${NAMESPACE:-kube-system}"
LANGGRAPH_API_URL="${LANGGRAPH_API_URL:-http://127.0.0.1:2024}"
PROMETHEUS_BASE_URL="${PROMETHEUS_BASE_URL:-http://host.docker.internal:30909}"

config_is_auto_value "${LANGGRAPH_THREAD_ID:-}" && LANGGRAPH_THREAD_ID=""
config_is_auto_value "${MCP_K8S_CONTAINER:-}" && MCP_K8S_CONTAINER=""
config_is_auto_value "${MCP_PROM_CONTAINER:-}" && MCP_PROM_CONTAINER=""
config_is_auto_value "${PROMETHEUS_BASE_URL:-}" && PROMETHEUS_BASE_URL=""

if [[ -z "${PROMETHEUS_BASE_URL:-}" ]]; then
  PROMETHEUS_BASE_URL="$(config_detect_prometheus_url "${KUBE_PROM_NODE_PORT:-30909}")"
fi

MCP_K8S_CONTAINER="${MCP_K8S_CONTAINER:-$(config_detect_mcp_container sentinel-x-mcp-k8s:latest)}"
MCP_PROM_CONTAINER="${MCP_PROM_CONTAINER:-$(config_detect_mcp_container sentinel-x-mcp-prometheus:latest)}"

if [[ -z "${LANGGRAPH_THREAD_ID:-}" ]] && [[ -x "${SENTINEL_ROOT}/.venv/bin/python" ]]; then
  LANGGRAPH_THREAD_ID="$(config_compute_thread_id "$SENTINEL_ROOT" "$CLUSTER_ID" "${TENANT_ID:-}")"
fi

GEN_HEADER="# GENERATED by sentinel-config-apply.sh — do not edit; edit ${ENV_MASTER} and re-run apply"

write_sync_k8s_env() {
  cat > /etc/sentinel/sync-k8s.env <<EOF
${GEN_HEADER}
SENTINEL_ROOT=${SENTINEL_ROOT}
LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
MCP_CONTAINER=${MCP_K8S_CONTAINER}
CLUSTER_ID=${CLUSTER_ID}
NAMESPACE=${NAMESPACE}
LANGGRAPH_THREAD_ID=${LANGGRAPH_THREAD_ID}
LANGGRAPH_SYNC_STATE_PATH=${LANGGRAPH_SYNC_STATE_PATH:-/var/lib/sentinel/sync-state}
LANGGRAPH_SYNC_INCREMENTAL=${LANGGRAPH_SYNC_INCREMENTAL:-1}
SENTINEL_SYNC_LOG=${SENTINEL_SYNC_LOG:-/var/log/sentinel-sync.log}
SENTINEL_PATROL_ENABLED=${SENTINEL_PATROL_ENABLED:-1}
SENTINEL_PATROL_DRY_RUN=${SENTINEL_PATROL_DRY_RUN:-true}
SENTINEL_PATROL_COOLDOWN_SEC=${SENTINEL_PATROL_COOLDOWN_SEC:-3600}
SENTINEL_PATROL_STATE_PATH=${SENTINEL_PATROL_STATE_PATH:-/var/lib/sentinel/inspect-patrol-state.json}
SENTINEL_PATROL_LOG=${SENTINEL_PATROL_LOG:-/var/log/sentinel-patrol.log}
SENTINEL_PATROL_EXTRA_NAMESPACES=${SENTINEL_PATROL_EXTRA_NAMESPACES:-sentinel-sandbox}
EOF
  chmod 600 /etc/sentinel/sync-k8s.env
  config_strip_crlf /etc/sentinel/sync-k8s.env
  config_log "wrote /etc/sentinel/sync-k8s.env"
}

write_langgraph_env() {
  cat > /etc/sentinel/sentinel-langgraph.env <<EOF
${GEN_HEADER}
SENTINEL_ROOT=${SENTINEL_ROOT}
SENTINEL_SANDBOX_ENABLED=${SENTINEL_SANDBOX_ENABLED:-1}
SENTINEL_SANDBOX_NAMESPACE=${SENTINEL_SANDBOX_NAMESPACE:-sentinel-sandbox}
SENTINEL_SANDBOX_IMAGE=${SENTINEL_SANDBOX_IMAGE:-sentinel-x-sandbox:latest}
SENTINEL_SANDBOX_AUDIT_DIR=${SENTINEL_SANDBOX_AUDIT_DIR:-${SENTINEL_ROOT}/sandbox/audit}
SENTINEL_SKILLS_DIR=${SENTINEL_SKILLS_DIR:-${SENTINEL_ROOT}/skills}
SENTINEL_SKILLS_DB=${SENTINEL_SKILLS_DB:-${SENTINEL_ROOT}/skills/.index/skills.db}
SENTINEL_SKILLS_RECORD=${SENTINEL_SKILLS_RECORD:-1}
SENTINEL_SKILLS_SEARCH_LIMIT=${SENTINEL_SKILLS_SEARCH_LIMIT:-3}
EOF
  chmod 600 /etc/sentinel/sentinel-langgraph.env
  config_strip_crlf /etc/sentinel/sentinel-langgraph.env
  config_log "wrote /etc/sentinel/sentinel-langgraph.env"
}

write_sync_prom_env() {
  [[ -n "${MCP_PROM_CONTAINER:-}" ]] || return 0
  cat > /etc/sentinel/sync-prom.env <<EOF
${GEN_HEADER}
SENTINEL_ROOT=${SENTINEL_ROOT}
LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
MCP_K8S_CONTAINER=${MCP_K8S_CONTAINER}
MCP_PROM_CONTAINER=${MCP_PROM_CONTAINER}
CLUSTER_ID=${CLUSTER_ID}
NAMESPACE=${NAMESPACE}
LANGGRAPH_THREAD_ID=${LANGGRAPH_THREAD_ID}
LANGGRAPH_SYNC_STATE_PATH=${LANGGRAPH_SYNC_STATE_PATH:-/var/lib/sentinel/sync-state}
LANGGRAPH_SYNC_INCREMENTAL=${LANGGRAPH_SYNC_INCREMENTAL:-1}
SENTINEL_PROM_SYNC_LOG=${SENTINEL_PROM_SYNC_LOG:-/var/log/sentinel-prom-sync.log}
EOF
  chmod 600 /etc/sentinel/sync-prom.env
  config_strip_crlf /etc/sentinel/sync-prom.env
  config_log "wrote /etc/sentinel/sync-prom.env"
}

write_ui_env() {
  cat > /etc/sentinel/sentinel-ui.env <<EOF
${GEN_HEADER}
LANGGRAPH_RUN_LIVE=1
LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
LANGGRAPH_THREAD_ID=${LANGGRAPH_THREAD_ID}
CLUSTER_ID=${CLUSTER_ID}
NAMESPACE=${NAMESPACE}
STREAMLIT_PORT=${STREAMLIT_PORT:-8501}
EOF
  chmod 600 /etc/sentinel/sentinel-ui.env
  config_strip_crlf /etc/sentinel/sentinel-ui.env
  config_log "wrote /etc/sentinel/sentinel-ui.env"
}

write_api_env() {
  cat > /etc/sentinel/sentinel-api.env <<EOF
${GEN_HEADER}
SENTINEL_ROOT=${SENTINEL_ROOT}
LANGGRAPH_API_URL=${LANGGRAPH_API_URL}
LANGGRAPH_THREAD_ID=${LANGGRAPH_THREAD_ID}
CLUSTER_ID=${CLUSTER_ID}
NAMESPACE=${NAMESPACE}
SENTINEL_PATROL_DRY_RUN=${SENTINEL_PATROL_DRY_RUN:-true}
SENTINEL_PATROL_COOLDOWN_SEC=${SENTINEL_PATROL_COOLDOWN_SEC:-3600}
EOF
  if [[ -n "${SENTINEL_API_TOKEN:-}" ]]; then
    echo "SENTINEL_API_TOKEN=${SENTINEL_API_TOKEN}" >>/etc/sentinel/sentinel-api.env
  fi
  chmod 600 /etc/sentinel/sentinel-api.env
  config_strip_crlf /etc/sentinel/sentinel-api.env
  config_log "wrote /etc/sentinel/sentinel-api.env"
}

write_mcp_env() {
  local mcp_env="${SENTINEL_ROOT}/mcp-servers/compose/.env"
  mkdir -p "$(dirname "$mcp_env")"
  if [[ ! -f "$mcp_env" ]] && [[ -f "${SENTINEL_ROOT}/mcp-servers/compose/.env.example" ]]; then
    cp "${SENTINEL_ROOT}/mcp-servers/compose/.env.example" "$mcp_env"
  fi
  [[ -f "$mcp_env" ]] || touch "$mcp_env"
  config_strip_crlf "$mcp_env"
  if grep -q '^PROMETHEUS_BASE_URL=' "$mcp_env"; then
    sed -i "s|^PROMETHEUS_BASE_URL=.*|PROMETHEUS_BASE_URL=${PROMETHEUS_BASE_URL}|" "$mcp_env"
  else
    echo "PROMETHEUS_BASE_URL=${PROMETHEUS_BASE_URL}" >>"$mcp_env"
  fi
  config_log "wrote $mcp_env"
}

mkdir -p /etc/sentinel
[[ -n "$MCP_K8S_CONTAINER" ]] || config_log "WARN: MCP K8s container not found"

write_sync_k8s_env
write_langgraph_env
write_mcp_env

if [[ "$WITH_PROM_SYNC" -eq 1 ]] || [[ -f /etc/sentinel/sync-prom.env ]]; then
  write_sync_prom_env
fi

if [[ "$WITH_UI" -eq 1 ]] || systemctl is-enabled sentinel-ui >/dev/null 2>&1; then
  write_ui_env
fi

if [[ "$WITH_API" -eq 1 ]] || systemctl is-enabled sentinel-api >/dev/null 2>&1; then
  write_api_env
fi

if [[ "$DO_RELOAD" -eq 1 ]]; then
  MCP_DIR="${SENTINEL_ROOT}/mcp-servers/compose"
  if [[ -d "$MCP_DIR" ]]; then
    DC="$(config_docker_compose)"
    bash -c "cd '$MCP_DIR' && unset PROMETHEUS_BASE_URL && $DC up -d --force-recreate mcp-prometheus" || config_log "WARN: mcp compose up failed"
  fi
  if [[ -f /etc/sentinel/sentinel-ui.env ]]; then
    unset PROMETHEUS_BASE_URL
    systemctl restart sentinel-ui 2>/dev/null || true
  fi
  if [[ -f /etc/sentinel/sentinel-api.env ]]; then
    systemctl restart sentinel-api 2>/dev/null || true
  fi
  systemctl restart sentinel-langgraph 2>/dev/null || config_log "WARN: sentinel-langgraph restart failed"
fi

config_log "apply complete; LANGGRAPH_THREAD_ID=${LANGGRAPH_THREAD_ID:-unset}"
